name: TheModernFarmacy
favicon: null
layout_spectrum: 0.09918682416900992
typography_spectrum: 0.385484506143257
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.95464604976587
  lightness: 0.164154363097623
  saturation: 0.8531850245781243
  rhythmicContrast: 0.20265476079657674
purpose: []
